
sudo: required

language: go

env:
- IMAGE="moriorgames/go-api"

services:
- docker

before_install:
- docker pull $IMAGE
- docker build -t $IMAGE .
- docker run -td --name go_api -p 8080:8080 $IMAGE

script: docker exec -ti go_api bash -c 'go test ./tests'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $IMAGE "${IMAGE}:${TRAVIS_COMMIT}"
- docker tag $IMAGE "${IMAGE}:latest"
- docker push "${IMAGE}:latest"
- docker push "${IMAGE}:${TRAVIS_COMMIT}"
